/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Checkin } from "./Checkin";
import { CheckinCountArgs } from "./CheckinCountArgs";
import { CheckinFindManyArgs } from "./CheckinFindManyArgs";
import { CheckinFindUniqueArgs } from "./CheckinFindUniqueArgs";
import { CreateCheckinArgs } from "./CreateCheckinArgs";
import { UpdateCheckinArgs } from "./UpdateCheckinArgs";
import { DeleteCheckinArgs } from "./DeleteCheckinArgs";
import { User } from "../../user/base/User";
import { CheckinService } from "../checkin.service";
@graphql.Resolver(() => Checkin)
export class CheckinResolverBase {
  constructor(protected readonly service: CheckinService) {}

  async _checkinsMeta(
    @graphql.Args() args: CheckinCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Checkin])
  async checkins(
    @graphql.Args() args: CheckinFindManyArgs
  ): Promise<Checkin[]> {
    return this.service.checkins(args);
  }

  @graphql.Query(() => Checkin, { nullable: true })
  async checkin(
    @graphql.Args() args: CheckinFindUniqueArgs
  ): Promise<Checkin | null> {
    const result = await this.service.checkin(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Checkin)
  async createCheckin(
    @graphql.Args() args: CreateCheckinArgs
  ): Promise<Checkin> {
    return await this.service.createCheckin({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Checkin)
  async updateCheckin(
    @graphql.Args() args: UpdateCheckinArgs
  ): Promise<Checkin | null> {
    try {
      return await this.service.updateCheckin({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Checkin)
  async deleteCheckin(
    @graphql.Args() args: DeleteCheckinArgs
  ): Promise<Checkin | null> {
    try {
      return await this.service.deleteCheckin(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Checkin): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
